# Generated by Django 5.1.6 on 2025-02-18 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizapp", "0007_alter_leaderboard_score"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExamControl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("exam_started", models.BooleanField(default=False)),
            ],
        ),
    ]
