# Generated by Django 5.1.6 on 2025-02-18 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizapp", "0008_examcontrol"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="question",
            field=models.TextField(),
        ),
    ]
